### ISSUE TITLE
Orders Chart - Y axis has no Min/Max

### ISSUE THREAD

**Issue by app-generator** [app-generator/django-argon-charts#5]
The Orders Chart is not showing any information regarding the Y axis:

![image](https://user-images.githubusercontent.com/51070104/114359633-d95e0680-9b7c-11eb-85ec-b3be6a0b8261.png)

The scale should be computed from 0 to MAX = Peek ORDERS value.

Here is the Widget layout extracted from the original template:

![image](https://user-images.githubusercontent.com/51070104/114359964-2f32ae80-9b7d-11eb-837b-35f7902ebe83.png)

**Comment by imankarimi** [comment]
#5 fixed: This happens because of the amount of data. To solve this problem, I changed the sample data.

**Comment by app-generator** [comment]
Fixed in [v0.0.1](https://github.com/app-generator/django-argon-charts/releases/tag/v0.0.1-rc1).
Closing this issue.
